### ISSUE TITLE
Quando faço isso recebo uma mensagem de erro

### ISSUE THREAD

**Issue by an-dutra** [MicrosoftDocs/sql-docs.pt-br#19]
Quando faço isso usando o mesmo usuário que outras pessoas recebo essa mensagem de erro:
Attempt to retrieve data for object failed for Server 'NomeDoBanco'.  (Microsoft.SqlServer.Smo)

------------------------------
For help, click: http://go.microsoft.com/fwlink?ProdName=Microsoft+SQL+Server&ProdVer=13.0.600.65+((SQL_Main).150920-0105)&EvtSrc=Microsoft.SqlServer.Management.Smo.ExceptionTemplates.FailedOperationExceptionText&EvtID=Attempt+to+retrieve+data+for+object+Server&LinkId=20476

------------------------------
Program Location:

   at Microsoft.SqlServer.Management.Smo.Server.GetSmoObject(Urn urn)
   at Microsoft.SqlServer.Management.UI.VSIntegration.ObjectExplorer.ScriptGenerator.ScriptCreate(SqlTextWriter sqlwriter, Server server, Urn[] urns, SqlScriptOptions options)
   at Microsoft.SqlServer.Management.UI.VSIntegration.ObjectExplorer.ScriptNodeActionContext.Script(SqlTextWriter writer)
   at Microsoft.SqlServer.Management.UI.VSIntegration.ObjectExplorer.SqlScriptMenu.OnScriptItemClick(Object sender, EventArgs e)

===================================

An exception occurred while executing a Transact-SQL statement or batch. (Microsoft.SqlServer.ConnectionInfo)

------------------------------
Program Location:

   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.ExecuteWithResults(String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.Execute(StringCollection query)
   at Microsoft.SqlServer.Management.Smo.PostProcessRemoteDataArchiveDatabaseProperties.GetRowResults(DataProvider dp, String propertyName)
   at Microsoft.SqlServer.Management.Smo.PostProcessRemoteDataArchiveDatabaseProperties.GetColumnData(String name, Object data, DataProvider dp)
   at Microsoft.SqlServer.Management.Smo.DataProvider.ManipulateRowDataPostProcess()
   at Microsoft.SqlServer.Management.Smo.DataProvider.GetTable()
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillData(ResultType resultType, StringCollection sql, Object connectionInfo, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Smo.DatabaseLevel.GetData(EnumResult res)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.GetInitDataReader(String[] fields, OrderBy[] orderby)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ImplInitialize(String[] fields, OrderBy[] orderby)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.Initialize(Boolean allProperties)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.OnPropertyMissing(String propname, Boolean useDefaultValue)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.RetrieveProperty(Int32 index, Boolean useDefaultOnMissingValue)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.GetPropertyObject(Int32 index)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.GetPropertyOptional(String propName)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.GetDbComparer(Boolean inServer)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitializeStringComparer()
   at Microsoft.SqlServer.Management.Smo.AbstractCollectionBase.get_StringComparer()
   at Microsoft.SqlServer.Management.Smo.SchemaCollectionBase.InitInnerCollection()
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.GetObjectByKey(ObjectKeyBase key)
   at Microsoft.SqlServer.Management.Smo.Server.GetSmoObjectRec(Urn urn)
   at Microsoft.SqlServer.Management.Smo.Server.GetSmoObject(Urn urn)

===================================

Invalid column name 'server_id'. (.Net SqlClient Data Provider)

------------------------------
For help, click: http://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&ProdVer=14.00.1000&EvtSrc=MSSQLServer&EvtID=207&LinkId=20476

------------------------------
Server Name: NomeDoBanco
Error Number: 207
Severity: 16
State: 1
Line Number: 7

------------------------------
Program Location:

   at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand)

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 6ebf3e22-9132-9a59-708b-ed3e4a350b69
* Version Independent ID: dec2e7f7-fd04-0070-0a71-6478f1e60d22
* Content: [Gerar scripts (SQL Server Management Studio) - SQL Server](https://docs.microsoft.com/pt-br/sql/ssms/scripting/generate-scripts-sql-server-management-studio?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/scripting/generate-scripts-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs.pt-br/blob/live/docs/ssms/scripting/generate-scripts-sql-server-management-studio.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by srvbpigh** [comment]
Hello, @an-dutra
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @an-dutra

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
